version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    labels:
      # http with redirection
      - traefik.http.middlewares.grav-redirect-middleware.redirectscheme.scheme=https
      - traefik.http.middlewares.grav-whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.0.0/16, 172.0.0.0/8

      - traefik.http.routers.grav-web-router.entrypoints=web
      - traefik.http.routers.grav-web-router.rule=Host(`grav.crowflock.com`)
      - traefik.http.routers.grav-web-router.middlewares=redirect-middleware
      # https
      
      - traefik.http.routers.grav-websecure-router.entrypoints=websecure
      - traefik.http.routers.grav-websecure-router.tls=true
      - traefik.http.routers.grav-websecure-router.rule=Host(`grav.crowflock.com`)
      - traefik.http.services.grav-websecure-router.loadbalancer.server.port=80
      - traefik.http.routers.grav-websecure-router.middlewares=grav-whitelist
    volumes:
      - data-volume:/config
    restart: unless-stopped
networks:
  default:
    name: traefik_default
    external: true
volumes:
  data-volume:
